### ISSUE TITLE
Missing resources

### ISSUE THREAD

**Issue by nixa92** [googlesamples/android-DirectShare#2]
R.layout.select_contact and R.id.list are missing from the project

**Comment by tjohns** [comment]
Thanks. Tracking upstream as issue 24104130.

**Comment by bytebeats** [comment]
Same problem.  Still unsolved?

**Comment by tjohns** [comment]
Yes, still unresolved. That's why this bug is still listed as open.

When it's fixed, we'll say it's fixed and close the bug. :)

**Comment by AndroidDeveloperLB** [comment]
Me too. Why was it removed?

**Comment by AungPyae** [comment]
@tjohns WHY it is not being fixed ?

**Comment by nixa92** [comment]
Here is a quick fix, until google make it right, change lines 46 and 53 in SelectContactActivity to:
.......
46        setContentView(android.R.layout.list_content);
.......
53        ListView list = (ListView) findViewById(android.R.id.list);
.......

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
