### ISSUE TITLE
Get error while building when minSDK =21 in build.gradle 

### ISSUE THREAD

**Issue by ajaybarvey** [googlesamples/android-DirectShare#3]
I have changed minSDK to 21 and I get the following error while running the app in Android Studio

:Application:compileDebugJavaWithJavac
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintAuthenticationDialogFragment.java:22: error: package android.hardware.fingerprint does not exist
import android.hardware.fingerprint.FingerprintManager;
                                   ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintUiHelper.java:21: error: package android.hardware.fingerprint does not exist
import android.hardware.fingerprint.FingerprintManager;
                                   ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintUiHelper.java:31: error: package FingerprintManager does not exist
public class FingerprintUiHelper extends FingerprintManager.AuthenticationCallback {
                                                           ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintAuthenticationDialogFragment.java:56: error: package FingerprintManager does not exist
    private FingerprintManager.CryptoObject mCryptoObject;
                              ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\MainActivity.java:23: error: package android.hardware.fingerprint does not exist
import android.hardware.fingerprint.FingerprintManager;
                                   ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\MainActivity.java:25: error: package android.security.keystore does not exist
import android.security.keystore.KeyGenParameterSpec;
                                ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\MainActivity.java:26: error: package android.security.keystore does not exist
import android.security.keystore.KeyPermanentlyInvalidatedException;
                                ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\MainActivity.java:27: error: package android.security.keystore does not exist
import android.security.keystore.KeyProperties;
                                ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintAuthenticationDialogFragment.java:149: error: package FingerprintManager does not exist
    public void setCryptoObject(FingerprintManager.CryptoObject cryptoObject) {
                                                  ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintUiHelper.java:36: error: cannot find symbol
    private final FingerprintManager mFingerprintManager;
                  ^
  symbol:   class FingerprintManager
  location: class FingerprintUiHelper
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintUiHelper.java:66: error: cannot find symbol
    private FingerprintUiHelper(FingerprintManager fingerprintManager,
                                ^
  symbol:   class FingerprintManager
  location: class FingerprintUiHelper
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintUiHelper.java:79: error: package FingerprintManager does not exist
    public void startListening(FingerprintManager.CryptoObject cryptoObject) {
                                                 ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintUiHelper.java:123: error: package FingerprintManager does not exist
    public void onAuthenticationSucceeded(FingerprintManager.AuthenticationResult result) {
                                                            ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\MainActivity.java:66: error: cannot find symbol
    @Inject FingerprintManager mFingerprintManager;
            ^
  symbol:   class FingerprintManager
  location: class MainActivity
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintUiHelper.java:49: error: cannot find symbol
        private final FingerprintManager mFingerPrintManager;
                      ^
  symbol:   class FingerprintManager
  location: class FingerprintUiHelperBuilder
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintUiHelper.java:52: error: cannot find symbol
        public FingerprintUiHelperBuilder(FingerprintManager fingerprintManager) {
                                          ^
  symbol:   class FingerprintManager
  location: class FingerprintUiHelperBuilder
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintModule.java:22: error: package android.hardware.fingerprint does not exist
import android.hardware.fingerprint.FingerprintManager;
                                   ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintModule.java:24: error: package android.security.keystore does not exist
import android.security.keystore.KeyProperties;
                                ^
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\src\main\java\com\example\android\fingerprintdialog\FingerprintModule.java:60: error: cannot find symbol
    public FingerprintManager providesFingerprintManager(Context context) {
           ^
  symbol:   class FingerprintManager
  location: class FingerprintModule
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\build\intermediates\classes\debug\com\example\android\fingerprintdialog\FingerprintModule$$ModuleAdapter.java:78: error: cannot find symbol
  public static final class ProvidesFingerprintManagerProvidesAdapter extends ProvidesBinding<FingerprintManager>
                                                                                              ^
  symbol:   class FingerprintManager
  location: class FingerprintModule$$ModuleAdapter
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\build\intermediates\classes\debug\com\example\android\fingerprintdialog\FingerprintModule$$ModuleAdapter.java:79: error: cannot find symbol
      implements Provider<FingerprintManager> {
                          ^
  symbol:   class FingerprintManager
  location: class FingerprintModule$$ModuleAdapter
C:\AWorking\Sandbox\android-FingerprintDialog-master\Application\build\intermediates\classes\debug\com\example\android\fingerprintdialog\FingerprintModule$$ModuleAdapter.java:113: error: cannot find symbol
    public FingerprintManager get() {
           ^
  symbol:   class FingerprintManager
  location: class ProvidesFingerprintManagerProvidesAdapter
error: Could not find injection type required by [com.example.android.fingerprintdialog.FingerprintUiHelper.FingerprintUiHelperBuilder, com.example.android.fingerprintdialog.MainActivity]
23 errors

 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':Application:compileDebugJavaWithJavac'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
