### ISSUE TITLE
Custom Intent Action

### ISSUE THREAD

**Issue by ghost** [googlesamples/android-DirectShare#4]
Hello.

Can I use Direct Share with my custom intent action e.g. com.myapp.MY_CUSTOM_INTENT?
The callback onGetChooserTargets don't call if I use custom Intent.

My code:

call chooser:
`val sharingIntent = Intent("com.myapp.MY_CUSTOM_INTENT")
sharingIntent.type = "text/plain"
sharingIntent.putExtra(android.content.Intent.EXTRA_TEXT, "sample text")
startActivity(Intent.createChooser(sharingIntent, "try share"))`

manifest file:
`<service
            android:name="com.myapp.data.MyChooserTargetService"
            android:label="@string/app_name"
            android:permission="android.permission.BIND_CHOOSER_TARGET_SERVICE">
            <intent-filter>
                <action android:name="android.service.chooser.ChooserTargetService" />
            </intent-filter>
        </service>`

`<activity android:name=".presentation.main.MainActivity"
            android:configChanges="orientation|keyboardHidden|screenSize"
            android:screenOrientation="portrait">
            <intent-filter>
                <action android:name="com.myapp.MY_CUSTOM_INTENT" />
                <category android:name="android.intent.category.DEFAULT" />
                <data android:mimeType="text/plain" />
            </intent-filter>
            <meta-data
                android:name="android.service.chooser.chooser_target_service"
                android:value="com.myapp.data.MyChooserTargetService" />
        </activity>`

my service:
`class MyChooserTargetService : ChooserTargetService() {

    override fun onGetChooserTargets(targetActivityName: ComponentName?, matchedFilter: IntentFilter?): MutableList<ChooserTarget> {
        val targets = ArrayList<ChooserTarget>()
        ...
        ...
        ...
        return targets
    }

}`

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
