### ISSUE TITLE
Direct Share

### ISSUE THREAD

**Issue by sathishkumar1392** [googlesamples/android-DirectShare#5]
Hi,
I have one query in Direct share sample. In direct share while user clicking share button icon it will shows all shared application in that i need to filter particular application in this feature.How to done with it..?

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
