### ISSUE TITLE
not working in Huawei devices (P9)

### ISSUE THREAD

**Issue by chlegou** [googlesamples/android-DirectShare#6]
i'm stuck in it for 2 days now, tried many codes for `Intent.createChooser()` , but didn't work, till i found this project and isn't working also!!

i'm getting always the huawei share intent instead of the wanted intent. (i have other installed apps, showing the wanted result, but my app (even this one) was always showing the samehuawei share intent.

Wanted Result: https://ibb.co/vVJFxH8

result i'm getting: https://ibb.co/qYMWFPt

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
